---
- name: add docker repository and update apt cache
  apt_repository: 
    repo: deb https://apt.dockerproject.org/repo ubuntu-xenial main
    update_cache: yes
    state: present

- name: install docker in ubuntu
  apt:
   name: docker-engine
   state: latest
   
- name: install docker-compose in ubuntu
  apt:
   name: docker-compose
   state: latest

- name: install packages for docker 
  apt: 
    name: '{{ item }}' 
    state: present
  
  with_items:
    - python-pip
    - docker-py

